version: "3.5"

services:

  mongo:
    container_name: nestauth_db
    image: mongo:latest
    restart: always
    volumes:
      - ${MONGO_DATA}:/data/db
      - ${MONGO_DUMP}:/dump
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - nesjs-network

  app:
    container_name: task-manager-api
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    links: 
      - mongo  
    depends_on:
      - mongo  
    networks:
      - nesjs-network

networks:
    nesjs-network:
      driver: bridge