name: 'Nest API - Project and Task Managements'

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['staging', 'master', 'develop']

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint
